export type ServiceProviderIndustryOption = {
  value: string
  label: string
}

export type ServiceProviderIndustryCategory = {
  id: string
  label: string
  options: ServiceProviderIndustryOption[]
}

export const SERVICE_PROVIDER_INDUSTRY_CATEGORIES: ServiceProviderIndustryCategory[] = [
  {
    id: 'construction_renovation',
    label: 'בנייה ושיפוצים',
    options: [
      { value: 'general_service_provider', label: 'נותן שירות כללי' },
      { value: 'renovation_contractor', label: 'קבלן שיפוצים' },
      { value: 'construction_contractor', label: 'קבלן בנייה' },
      { value: 'structural_contractor', label: 'קבלן שלד' },
      { value: 'finish_contractor', label: 'קבלן גמר' },
      { value: 'site_manager', label: 'מנהל עבודה בנייה' },
      { value: 'construction_supervisor', label: 'מפקח בנייה' },
      { value: 'land_surveyor', label: 'מודד שטח' },
      { value: 'construction_safety_consultant', label: 'יועץ בטיחות בנייה' },
      { value: 'tiler', label: 'רצף' },
      { value: 'parquet_installer', label: 'מתקין פרקטים' },
      { value: 'carpet_installer', label: 'מתקין שטיחים' },
      { value: 'wall_cladding_installer', label: 'חיפוי קירות' },
      { value: 'drywall_installer', label: 'עבודות גבס' },
      { value: 'painter', label: 'צבעי' },
      { value: 'plasterer', label: 'טייח' },
      { value: 'window_installer', label: 'מתקין חלונות' },
      { value: 'shutter_installer', label: 'מתקין תריסים' },
      { value: 'door_installer', label: 'מתקין דלתות' },
      { value: 'electrician', label: 'חשמלאי' },
      { value: 'smart_home_installer', label: 'מתקין מערכות חשמל חכם' },
      { value: 'cctv_installer', label: 'מתקין מצלמות אבטחה' },
      { value: 'alarm_installer', label: 'מתקין אזעקות' },
      { value: 'plumber', label: 'אינסטלטור' },
      { value: 'solar_heater_installer', label: 'מתקין דודי שמש' },
      { value: 'water_filter_installer', label: 'מתקין מערכות סינון מים' },
      { value: 'gas_system_installer', label: 'מתקין מערכות גז' },
      { value: 'gardener', label: 'גנן' },
      { value: 'synthetic_grass_installer', label: 'מתקין דשא סינטטי' },
      { value: 'tree_trimmer', label: 'גוזם עצים' },
      { value: 'landscape_contractor', label: 'קבלן גינון' },
      { value: 'outdoor_development_contractor', label: 'קבלן פיתוח חוץ' },
      { value: 'pergola_deck_installer', label: 'מתקין פרגולות ודקים' },
      { value: 'waterproofing_contractor', label: 'קבלן איטום' },
    ],
  },
  {
    id: 'transport_logistics',
    label: 'תחבורה והובלות',
    options: [
      { value: 'taxi_driver', label: 'נהג מונית' },
      { value: 'shuttle_driver', label: 'נהג הסעות' },
      { value: 'delivery_driver', label: 'נהג שליחויות' },
      { value: 'freelance_courier', label: 'שליח עצמאי' },
      { value: 'small_courier_company', label: 'חברת שליחויות קטנה' },
      { value: 'apartment_mover', label: 'מוביל דירות' },
      { value: 'office_mover', label: 'מוביל משרדים' },
      { value: 'crane_service', label: 'שירותי מנוף' },
      { value: 'towing_service', label: 'שירותי גרר' },
      { value: 'auto_mechanic', label: 'מכונאי רכב' },
      { value: 'auto_body_technician', label: 'פחח' },
      { value: 'auto_electrician', label: 'חשמלאי רכב' },
    ],
  },
  {
    id: 'maintenance_home_services',
    label: 'תחזוקה ושירותי בית',
    options: [
      { value: 'home_cleaner', label: 'מנקה בתים' },
      { value: 'office_cleaner', label: 'מנקה משרדים' },
      { value: 'cleaning_company', label: 'חברת ניקיון' },
      { value: 'sofa_cleaning', label: 'ניקוי ספות' },
      { value: 'carpet_cleaning', label: 'ניקוי שטיחים' },
      { value: 'high_rise_window_cleaning', label: 'ניקוי חלונות בגובה' },
      { value: 'pest_control', label: 'הדברה' },
      { value: 'snake_catcher', label: 'לוכד נחשים' },
      { value: 'hvac_technician', label: 'טכנאי מזגנים' },
      { value: 'refrigerator_technician', label: 'טכנאי מקררים' },
      { value: 'washer_technician', label: 'טכנאי מכונות כביסה' },
      { value: 'oven_technician', label: 'טכנאי תנורים' },
      { value: 'computer_technician', label: 'טכנאי מחשבים' },
    ],
  },
  {
    id: 'digital_technology',
    label: 'דיגיטל וטכנולוגיה',
    options: [
      { value: 'software_developer', label: 'מתכנת' },
      { value: 'app_developer', label: 'מפתח אפליקציות' },
      { value: 'web_developer', label: 'מפתח אתרים' },
      { value: 'cyber_security_specialist', label: 'מומחה סייבר' },
      { value: 'devops_engineer', label: 'DevOps' },
      { value: 'data_analyst', label: 'דאטה אנליסט' },
      { value: 'data_scientist', label: 'דאטה סיינטיסט' },
      { value: 'ai_specialist', label: 'מומחה AI' },
      { value: 'it_specialist', label: 'איש IT' },
      { value: 'network_installer', label: 'מתקין רשתות' },
      { value: 'cloud_specialist', label: 'מומחה ענן' },
    ],
  },
  {
    id: 'marketing_design_creative',
    label: 'שיווק, קריאייטיב ועיצוב',
    options: [
      { value: 'graphic_designer', label: 'גרפיקאי' },
      { value: 'ui_ux_designer', label: 'מעצב UI/UX' },
      { value: 'interior_designer', label: 'מעצב פנים' },
      { value: 'product_designer', label: 'מעצב מוצר' },
      { value: 'video_editor', label: 'עורך וידאו' },
      { value: 'photographer', label: 'צלם' },
      { value: 'wedding_photographer', label: 'צלם חתונות' },
      { value: 'copywriter', label: 'קופירייטר' },
      { value: 'content_writer', label: 'כותב תוכן' },
      { value: 'social_media_manager', label: 'מנהל סושיאל' },
      { value: 'seo_specialist', label: 'מומחה SEO' },
      { value: 'ppc_specialist', label: 'מומחה PPC' },
      { value: 'campaign_manager', label: 'מנהל קמפיינים' },
    ],
  },
  {
    id: 'licensed_professions',
    label: 'מקצועות חופשיים',
    options: [
      { value: 'lawyer', label: 'עורך דין' },
      { value: 'accountant', label: 'רואה חשבון' },
      { value: 'tax_consultant', label: 'יועץ מס' },
      { value: 'appraiser', label: 'שמאי' },
      { value: 'engineer', label: 'מהנדס' },
      { value: 'architect', label: 'אדריכל' },
      { value: 'practical_engineer', label: 'הנדסאי' },
      { value: 'economist', label: 'כלכלן' },
      { value: 'insurance_agent', label: 'סוכן ביטוח' },
      { value: 'private_investigator', label: 'חוקר פרטי' },
      { value: 'bookkeeper', label: 'מנהל חשבונות' },
      { value: 'translator', label: 'מתורגמן' },
    ],
  },
  {
    id: 'health_therapy',
    label: 'בריאות וטיפול',
    options: [
      { value: 'private_doctor', label: 'רופא פרטי' },
      { value: 'dentist', label: 'רופא שיניים' },
      { value: 'psychologist', label: 'פסיכולוג' },
      { value: 'physiotherapist', label: 'פיזיותרפיסט' },
      { value: 'speech_therapist', label: 'קלינאי תקשורת' },
      { value: 'occupational_therapist', label: 'מרפא בעיסוק' },
      { value: 'veterinarian', label: 'וטרינר' },
      { value: 'alternative_medicine', label: 'רפואה משלימה' },
      { value: 'massage_therapist', label: 'מעסה' },
      { value: 'reflexologist', label: 'רפלקסולוג' },
      { value: 'naturopath', label: 'נטורופת' },
      { value: 'acupuncture_specialist', label: 'דיקור סיני' },
      { value: 'personal_fitness_trainer', label: 'מאמן כושר אישי' },
      { value: 'yoga_pilates_instructor', label: 'מדריך יוגה / פילאטיס' },
    ],
  },
  {
    id: 'education_training',
    label: 'חינוך והדרכה',
    options: [
      { value: 'private_teacher', label: 'מורה פרטי' },
      { value: 'piano_teacher', label: 'מורה לפסנתר' },
      { value: 'piano_tuner', label: 'מכוון פסנתרים' },
      { value: 'driving_instructor', label: 'מדריך נהיגה' },
      { value: 'swimming_instructor', label: 'מדריך שחייה' },
      { value: 'fitness_instructor', label: 'מדריך כושר' },
      { value: 'online_course_instructor', label: 'מדריך קורסים אונליין' },
      { value: 'private_lecturer', label: 'מרצה פרטי' },
      { value: 'sports_instructor', label: 'מדריך ספורט' },
    ],
  },
  {
    id: 'consulting_business_personal',
    label: 'ייעוץ עסקי ואישי',
    options: [
      { value: 'business_consultant', label: 'יועץ עסקי' },
      { value: 'organizational_consultant', label: 'יועץ ארגוני' },
      { value: 'marketing_consultant', label: 'יועץ שיווק' },
      { value: 'financial_consultant', label: 'יועץ פיננסי' },
      { value: 'mortgage_consultant', label: 'יועץ משכנתאות' },
      { value: 'real_estate_consultant', label: 'יועץ נדל״ן' },
      { value: 'career_consultant', label: 'יועץ קריירה' },
      { value: 'personal_coach', label: 'מאמן אישי' },
    ],
  },
  {
    id: 'arts_entertainment',
    label: 'אומנות ופנאי',
    options: [
      { value: 'musician', label: 'מוזיקאי' },
      { value: 'dj', label: 'DJ' },
      { value: 'singer', label: 'זמר' },
      { value: 'actor', label: 'שחקן' },
      { value: 'standup_comedian', label: 'סטנדאפיסט' },
      { value: 'painter_artist', label: 'אמן ציור' },
      { value: 'sculptor', label: 'פסל' },
      { value: 'birthday_entertainer', label: 'מפעיל ימי הולדת' },
      { value: 'clown', label: 'ליצן' },
      { value: 'magician', label: 'קוסם' },
    ],
  },
  {
    id: 'everyday_small_services',
    label: 'שירותים קטנים יומיומיים',
    options: [
      { value: 'seamstress', label: 'תופרת' },
      { value: 'tailor', label: 'חייט' },
      { value: 'hairdresser', label: 'ספר' },
      { value: 'cosmetician', label: 'קוסמטיקאית' },
      { value: 'manicurist', label: 'מניקוריסטית' },
      { value: 'pedicurist', label: 'פדיקוריסטית' },
      { value: 'makeup_artist', label: 'מאפרת' },
      { value: 'dog_groomer', label: 'ספר כלבים' },
      { value: 'dog_trainer', label: 'מאלף כלבים' },
    ],
  },
]

